name: Auto Deploy to aaPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Trigger aaPanel Webhook
        run: |
          echo "🚀 Sending deploy request to aaPanel..."
          curl -X POST "${{ secrets.AAPANEL_WEBHOOK_URL }}"'
               
      - name: Notify success
        if: success()
        run: |
          curl -d "🚀 Deploy thành công cho ${{ github.repository }}!" ntfy.sh/${{ secrets.NTFY_TOPIC }}
      
      - name: Notify failure
        if: failure()
        run: |
          curl -d "❌ Deploy thất bại cho ${{ github.repository }}!" ntfy.sh/${{ secrets.NTFY_TOPIC }}
