name: Auto Deploy to aaPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Trigger aaPanel Webhook
        run: |
          echo "🚀 Sending deploy request to aaPanel..."
          curl -X POST "${{ secrets.AAPANEL_WEBHOOK_URL }}" \
               -H "Content-Type: application/json" \
               -d '{"event": "github_push", "status": "triggered"}'
      - name: Notify via ntfy
        run: |
          curl -d "🚀 Deploy thành công cho ${{ github.repository }}!" ntfy.sh/tunnapi-git-pulls
