name: Auto Deploy to aaPanel

on:
  push:
    branches: [ main ]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: michaelw90/PHP-Lint@master
  deploy:
    needs: [phplint]  # Only run if phplint succeeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to aaPanel
        uses: tunnaduong/aapanel-deploy-action@v1.1
        with:
          panel_url: https://server.tunnaduong.com
          webhook_key: ${{ secrets.AAPANEL_WEBHOOK_KEY }}
          ntfy_topic: tunnapi-git-pulls
